package com.eventreport.report;

abstract class Report {
    protected int eventId;        // ID of the event for which the report is generated
    protected String reportData;  // Data for the report, which will be generated by subclasses

    // Constructor
    public Report(int eventId) {
        this.eventId = eventId;
        this.reportData = ""; // Initialize with an empty string
    }

    // Abstract method to generate the report
    // This will be implemented by subclasses to provide specific report details
    public abstract void generateReport();

    // Method to display the report
    public void displayReport() {
        System.out.println("Event ID: " + eventId);
        System.out.println("Report Data:\n" + reportData);
    }

    // Method to save the report as a text file
    public void saveReport(String filename) {
        try (java.io.FileWriter writer = new java.io.FileWriter(filename)) {
            writer.write("Event ID: " + eventId + "\n");
            writer.write("Report Data:\n" + reportData + "\n");
            System.out.println("Report saved as " + filename);
        } catch (java.io.IOException e) {
            System.out.println("Error saving report: " + e.getMessage());
        }
    }
}
